//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingCard.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string btnSaveNewCategory {
            get {
                return ResourceManager.GetString("btnSaveNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Item.
        /// </summary>
        public static string btnSaveNewItem {
            get {
                return ResourceManager.GetString("btnSaveNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Password.
        /// </summary>
        public static string btnSaveNewPassword {
            get {
                return ResourceManager.GetString("btnSaveNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New Role.
        /// </summary>
        public static string btnSaveNewRole {
            get {
                return ResourceManager.GetString("btnSaveNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SubCategory.
        /// </summary>
        public static string btnSaveNewSubCategory {
            get {
                return ResourceManager.GetString("btnSaveNewSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New User.
        /// </summary>
        public static string btnSaveNewUser {
            get {
                return ResourceManager.GetString("btnSaveNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangPassword {
            get {
                return ResourceManager.GetString("ChangPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string InEvents {
            get {
                return ResourceManager.GetString("InEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Image.
        /// </summary>
        public static string LableCategoryImage {
            get {
                return ResourceManager.GetString("LableCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lableCategoryName {
            get {
                return ResourceManager.GetString("lableCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LableDescription {
            get {
                return ResourceManager.GetString("LableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string LableHomePage {
            get {
                return ResourceManager.GetString("LableHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Image.
        /// </summary>
        public static string LableItemImage {
            get {
                return ResourceManager.GetString("LableItemImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mange users.
        /// </summary>
        public static string LableMange {
            get {
                return ResourceManager.GetString("LableMange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Compar New Password.
        /// </summary>
        public static string LableNewComparPassword {
            get {
                return ResourceManager.GetString("LableNewComparPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string LableNewPassword {
            get {
                return ResourceManager.GetString("LableNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string LableOldPassword {
            get {
                return ResourceManager.GetString("LableOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LablePrice {
            get {
                return ResourceManager.GetString("LablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string LableRoleName {
            get {
                return ResourceManager.GetString("LableRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Collection.
        /// </summary>
        public static string LableRoleUser {
            get {
                return ResourceManager.GetString("LableRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string LableSelectCategory {
            get {
                return ResourceManager.GetString("LableSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User Role.
        /// </summary>
        public static string LableSelectUserRole {
            get {
                return ResourceManager.GetString("LableSelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LableTitle {
            get {
                return ResourceManager.GetString("LableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LableUser {
            get {
                return ResourceManager.GetString("LableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active User.
        /// </summary>
        public static string LableUserActive {
            get {
                return ResourceManager.GetString("LableUserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string LableUserEmail {
            get {
                return ResourceManager.GetString("LableUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Image.
        /// </summary>
        public static string LableUserImage {
            get {
                return ResourceManager.GetString("LableUserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LableUserName {
            get {
                return ResourceManager.GetString("LableUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LableUserPassword {
            get {
                return ResourceManager.GetString("LableUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Password.
        /// </summary>
        public static string LableUseruserComparePassword {
            get {
                return ResourceManager.GetString("LableUseruserComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
    }
}
